### PR TITLE
Allow symfony 5

### PR DESCRIPTION
**Pull request by mihaileu**
make compatible with symfony 5

### CODE REVIEW

**Comment by theofidry** [comment]
Thanks for working on this! Looks like the CI needs to be updated a bit as well but otherwise looks good

**Comment by mihaileu** [comment]
https://github.com/bobthecow/psysh/pull/577
Need to wait for this merge to happen

**Comment by mihaileu** [comment]
@theofidry , could you please restart the build ?

**Comment by theofidry** [comment]
done

**Comment by theofidry** [comment]
Thank you @mihaileu

**Pull request merged**
