### PR TITLE
Use the test.xml of the FrameworkBundle

### PR DESCRIPTION
**Pull request by maxhelias**

### CODE REVIEW

**Comment by maxhelias** [comment]
There is still a small problem with the container that is not able to recover the services of another bundle.
At this moment `$containerId = $container->has('test.service_container') ? 'test.service_container' : 'service_container';`, the condition is always wrong.
I will investigate a little more

**Comment by theofidry** [comment]
I don't remember this PR at all: is it still relevant in which case can this be updated?

**Comment by maxhelias** [comment]
Hi! Don't worry me too 😅 
I think yes, this will allow us to follow the test configuration of Symfony, to warn us in case of BC and avoid late duplication

**Comment by theofidry** [comment]
Guess I have trouble with this PR :(

So if I understand correctly Psysh will use the test container instead of the regular one allowing to access to services that might otherwise get inlined in the regular container is that right?

Is that test container available in dev as well?

**Comment by theofidry** [comment]
Tested locally, looks good. Thanks! :)

**Comment by maxhelias** [comment]
@theofidry This is correct for the first one and it will follow the evolution of Symfony.

And I don't think it's available in dev because it's only available with the `framework.test: true` option

**Comment by theofidry** [comment]
Seems to be working fine in dev as well

**Pull request merged**
